apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-gitops-root
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/partojalili/ACMClusterProvisioningWithGitOps.git
    targetRevision: HEAD
    path: applicationsets
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
