apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: day2-rbac
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: gitops-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: '{{name}}-rbac'
    spec:
      project: default
      source:
        repoURL: https://github.com/YOUR_ORG/ACMClusterProvisioningWithGitOps.git
        targetRevision: HEAD
        path: day2-config/rbac
      destination:
        server: '{{server}}'
        namespace: ''
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
