apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-provisioning-appset.yaml
  - day2-logging-appset.yaml
  - day2-network-policies-appset.yaml
  - day2-rbac-appset.yaml
