apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  creationTimestamp: "2026-05-04T23:30:24Z"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  generation: 413
  name: prod-cluster
  namespace: openshift-gitops
  ownerReferences:
  - apiVersion: argoproj.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: ApplicationSet
    name: cluster-provisioning
    uid: e1e5231c-1380-4000-b434-6fa63867aaf3
  resourceVersion: "1393119"
  uid: bfea8ac5-1609-40ba-bd80-4c5637debb86
operation:
  initiatedBy:
    automated: true
  retry:
    limit: 5
  sync:
    prune: true
    revision: 340298a4f91f1de838048cf2d1da4a9aebb80b2d
    source:
      path: clusters/overlays/prod
      repoURL: https://github.com/partojalili/ACMClusterProvisioningWithGitOps.git
      targetRevision: HEAD
    syncOptions:
    - CreateNamespace=true
spec:
  destination:
    namespace: prod-cluster
    server: https://kubernetes.default.svc
  project: default
  source:
    path: clusters/overlays/prod
    repoURL: https://github.com/partojalili/ACMClusterProvisioningWithGitOps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
status:
  controllerNamespace: openshift-gitops
  health:
    lastTransitionTime: "2026-05-04T23:30:24Z"
    status: Healthy
  operationState:
    finishedAt: "2026-05-05T18:13:06Z"
    message: 'one or more objects failed to apply, reason: admission webhook "machinepoolvalidators.admission.hive.openshift.io"
      denied the request: MachinePool.hive.openshift.io "prod-cluster-worker" is invalid:
      spec.replicas: Invalid value: 5: replicas must not be specified when autoscaling
      is specified. Retrying attempt #5 at 6:14PM.'
    operation:
      initiatedBy:
        automated: true
      retry:
        limit: 5
      sync:
        prune: true
        revision: 340298a4f91f1de838048cf2d1da4a9aebb80b2d
        source:
          path: clusters/overlays/prod
          repoURL: https://github.com/partojalili/ACMClusterProvisioningWithGitOps.git
          targetRevision: HEAD
        syncOptions:
        - CreateNamespace=true
    phase: Running
    retryCount: 5
    startedAt: "2026-05-05T18:10:18Z"
    syncResult:
      resources:
      - group: ""
        hookPhase: Running
        kind: Secret
        message: secret/ssh-private-key configured
        name: ssh-private-key
        namespace: prod-cluster
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Secret
        message: secret/install-config configured
        name: install-config
        namespace: prod-cluster
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Secret
        message: secret/aws-credentials configured
        name: aws-credentials
        namespace: prod-cluster
        status: Synced
        syncPhase: Sync
        version: v1
      - group: ""
        hookPhase: Running
        kind: Secret
        message: secret/pull-secret configured
        name: pull-secret
        namespace: prod-cluster
        status: Synced
        syncPhase: Sync
        version: v1
      - group: agent.open-cluster-management.io
        hookPhase: Running
        kind: KlusterletAddonConfig
        message: klusterletaddonconfig.agent.open-cluster-management.io/prod-cluster
          unchanged
        name: prod-cluster
        namespace: prod-cluster
        status: Synced
        syncPhase: Sync
        version: v1
      - group: cluster.open-cluster-management.io
        hookPhase: Running
        kind: ManagedCluster
        message: managedcluster.cluster.open-cluster-management.io/prod-cluster unchanged
        name: prod-cluster
        namespace: prod-cluster
        status: Synced
        syncPhase: Sync
        version: v1
      - group: hive.openshift.io
        hookPhase: Running
        kind: ClusterDeployment
        message: clusterdeployment.hive.openshift.io/prod-cluster unchanged
        name: prod-cluster
        namespace: prod-cluster
        status: Synced
        syncPhase: Sync
        version: v1
      - group: hive.openshift.io
        hookPhase: Failed
        kind: MachinePool
        message: 'admission webhook "machinepoolvalidators.admission.hive.openshift.io"
          denied the request: MachinePool.hive.openshift.io "prod-cluster-worker"
          is invalid: spec.replicas: Invalid value: 5: replicas must not be specified
          when autoscaling is specified'
        name: prod-cluster-worker
        namespace: prod-cluster
        status: SyncFailed
        syncPhase: Sync
        version: v1
      revision: 340298a4f91f1de838048cf2d1da4a9aebb80b2d
      source:
        path: clusters/overlays/prod
        repoURL: https://github.com/partojalili/ACMClusterProvisioningWithGitOps.git
        targetRevision: HEAD
  reconciledAt: "2026-05-05T18:13:02Z"
  resources:
  - kind: Secret
    name: aws-credentials
    namespace: prod-cluster
    status: Synced
    version: v1
  - kind: Secret
    name: install-config
    namespace: prod-cluster
    status: Synced
    version: v1
  - kind: Secret
    name: pull-secret
    namespace: prod-cluster
    status: Synced
    version: v1
  - kind: Secret
    name: ssh-private-key
    namespace: prod-cluster
    status: Synced
    version: v1
  - group: agent.open-cluster-management.io
    kind: KlusterletAddonConfig
    name: prod-cluster
    namespace: prod-cluster
    status: Synced
    version: v1
  - group: cluster.open-cluster-management.io
    kind: ManagedCluster
    name: prod-cluster
    status: Synced
    version: v1
  - group: hive.openshift.io
    kind: ClusterDeployment
    name: prod-cluster
    namespace: prod-cluster
    status: Synced
    version: v1
  - group: hive.openshift.io
    health:
      status: Missing
    kind: MachinePool
    name: prod-cluster-worker
    namespace: prod-cluster
    status: OutOfSync
    version: v1
  sourceHydrator: {}
  sourceType: Kustomize
  summary: {}
  sync:
    comparedTo:
      destination:
        namespace: prod-cluster
        server: https://kubernetes.default.svc
      source:
        path: clusters/overlays/prod
        repoURL: https://github.com/partojalili/ACMClusterProvisioningWithGitOps.git
        targetRevision: HEAD
    revision: 340298a4f91f1de838048cf2d1da4a9aebb80b2d
    status: OutOfSync
