apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- operator-group.yaml
- subscription.yaml
- loki-operator-namespace.yaml
- loki-operator-subscription.yaml
- lokistack.yaml
- cluster-log-forwarder.yaml
